library(usethis)
library(available)
library(formatR)
library(roxygen2)
library(devtools)
use_github(protocol = "https", auth_token = "a8695797dccc272508bcdb9fc5b312a63ae6ccb3")

use_package_doc()
use_vignette("fineng-vignette")
use_readme_rmd()
use_description()
use_rcpp()
