# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
timesTwo <- function(x) {
    .Call('_fineng_timesTwo', PACKAGE = 'fineng', x)
}

#' @export
timesfive <- function(x) {
    .Call('_fineng_timesfive', PACKAGE = 'fineng', x)
}

